### PR TITLE
L223.electricity

### PR DESCRIPTION
**Pull request by cwroney**
#517 

For the moment, I removed the two extra lines from A23.globaltech_eff.csv to enable the merge and match the old data system. We should still figure out why those lines (two lines on backup electricity efficiency for PV and CSP) were changed in some version of the old data system (they're in the 4.3 release version I downloaded from Github in June but not the data system used here). Something for when I have more budgeted time on this. 

Also, it's throwing warnings about the temp-data-inject of these outputs into the GCAM_USA and Water electricity chunks. Not sure if I should be going in and adjusting those, but I didn't want to go over time.

### CODE REVIEW

**Comment by bpbond** [comment]
I have made some minor tweaks and some bigger changes: in particular, both this chunk and `LA118.hydro` were leaving `year` as character, not numeric, in many data objects, which broke the downstream `L2233.electricity_water` file.

All the `temp-data-inject`s are now removed, but `L2233.electricity_water` is throwing an error because of NULL objects. It may be the `grepl` calls at lines 304-305 aren't working correctly now? Not sure yet. @swd-turner if you have time to look at this please do. Otherwise @cwroney you and I can come back to this next week.

**Comment by cwroney** [comment]
@bpbond Haven't spent any time on this (don't worry), but possibly related to the same conditional output issue over here, https://github.com/JGCRI/gcamdata/issues/797? This chunk is definitely making some empty tibbles.

**Comment by swd-turner** [comment]
@bpbond Ok - I'll look into these downstream errors in `L2233.electricity_water` tomorrow.

**Comment by swd-turner** [comment]
@bpbond you're correct that the `grepl` calls on lines 304-305 are the problem. When the inputs are temp-inject the `get_title` call returns the actual name of the object, which is the string we want to search. But with the new objects fed in from upstream, `get_title` searches the title written by whoever coded the output. The fix is just to change from `get_title` to `get_legacy_name` in these lines. I'll commit this change shortly along with the other updates to the attributes for `L2233.electricity_water` outputs -- see issue #648.

**Comment by bpbond** [comment]
Ah awesome, thank you!

**Comment by ssmithClimate** [comment]
On the first comment regarding the lines for two lines on backup electricity efficiency for PV and CSP), if that's in 4.3, is there a way of documenting that change in the .csv somewhere other than just removing those lines so that change doesn't just mysteriously happen? (Also @skim301 has spent a lot of time looking at renewables lately, he might have some insights.)

**Comment by bpbond** [comment]
Any other comments @ssmithClimate ? If this OK to merge please approve. Thanks.

**Comment by ssmithClimate** [comment]
@bpbond I haven't looked through the code yet, but will try to do this later today.

**Comment by bpbond** [comment]
Thanks Steve! Chris - when you get a chance, please address these comments, and we'll get this merged.

**Comment by bpbond** [comment]
@cwroney This is failing a timeshift test, looks like.

**Comment by cwroney** [comment]
@bpbond The timeshift is passing on my machine. Not sure what's going on with it!

**Pull request merged**
