### PR TITLE
Snyder_LB122_again per suggestion of RPL, added ungroup() to slow pipeline

### PR DESCRIPTION
**Pull request by abigailsnyder**
Speeds things up a ton, still passes Test Package and Check Package

### CODE REVIEW

**Comment by abigailsnyder** [comment]
Specifically, chunk LB122.LC_R_Cropland_Yh_GLU

Added `ungroup()` on line 463; only change.

Test and Check fine on my machine at least.

**Comment by bpbond** [comment]
Oh interesting. So before `complete` was operating within groups, so that really slowed things down? How much of a speedup, do you know?

**Comment by abigailsnyder** [comment]
When I would run driver, this chunk usually had a "make" between 7 and 8 (it was that big gross progress bar). Now it's a little less than 1.

**Comment by abigailsnyder** [comment]
quoting RPL on slack dsr channel:  "Putting an `ungroup` at the beginning of the pipeline cuts the total chunk time down from 5840ms to 920ms."

**Comment by bpbond** [comment]
Awesome!

**Comment by bpbond** [comment]
@abigailsnyder maybe add this to the "Hints" page, or somewhere else, on the wiki? Would be good for people to know and understand this.

**Pull request merged**
