### PR TITLE
OLDNEW-LB122.LC_R_Cropland_Yh_GLU

### PR DESCRIPTION
**Pull request by russellhz**
Removed two manual changes to match old data system. 

This changes values on a bunch of downstream files.

Changed files:
1. L122.ag_EcYield_kgm2_R_C_Y_GLU
2. L122.ag_HA_to_CropLand_R_Y_GLU
3. L122.EmissShare_R_C_Y_GLU
4. L122.ghg_tg_R_agr_C_Y_GLU
5. L122.LC_bm2_R_HarvCropLand_C_Yh_GLU
6. L122.LC_bm2_R_HarvCropLand_Yh_GLU
7. L122.LC_bm2_R_OtherArableLand_Yh_GLU
8. L1221.ghg_tg_R_agr_C_Y_GLU_IRR
9. L125.LC_bm2_R_LT_Yh_GLU
10. L131.LV_USD75_m2_R_GLU
11. L171.ag_irrEcYield_kgm2_R_C_Y_GLU
12. L171.ag_rfdEcYield_kgm2_R_C_Y_GLU
13. L171.LC_bm2_R_irrHarvCropLand_C_Yh_GLU
14. L171. LC_bm2_R_rfdHarvCropLand_C_Yh_GLU
15. L181.ag_EcYield_kgm2_R_C_Y_GLU_irr_level
16. L181.LC_bm2_R_C_Yh_GLU_irr_level
17. L2012.AgHAtoCL_irr_mgmt
18. L221.LN1_ValueLogit
19. L2231.LN3_HistUnmgdAllocation
20. L2231.LN3_UnmgdAllocation
21. L2252.LN5_HistMgdAllocation_crop
22. L2252.LN5_MgdAllocation_crop
23. L2252.LN5_MgdCarbon_crop

### CODE REVIEW

**Comment by bpbond** [comment]
Thanks. Seems straightforward but please do post some stats or graphs on how much the data values in those outputs change.

**Comment by russellhz** [comment]
Nothing looks like too big a change here. The one change with large absolute differences (unManagedLandValue) has very small percent differences

lb122

**Comment by bpbond** [comment]
Looks good to me but also tagging Kate.

**Comment by bpbond** [comment]
Hmm, Travis is downloading the latest `gcamdata.compdata`, but still failing the oldnew test.

**Pull request merged**
