### PR TITLE
Shift to new "Authors@R" in DESCRIPTION

### PR DESCRIPTION
**Pull request by bpbond**
See http://r-pkgs.had.co.nz/description.html#author for more information.

### CODE REVIEW

**Comment by bpbond** [comment]
@kvcalvin @rynacui @kdorheim @fengly20 @jhoring @russellhz @pkyle @rplzzz @pralitp @cwroney @abigailsnyder @aarony2j @swd-turner 

If you have an [ORCID ID](https://orcid.org) (which I highly recommend), feel free to add it to this PR.

**Comment by pkyle** [comment]
@bpbond should we also include our email addresses?

**Comment by bpbond** [comment]
I'd say not necessary, but you can if you want.

**Comment by bpbond** [comment]
@rhoesly @mihejazi @gokuliyer @skim301 @yalingliupnnl @d3y419 @ssmithClimate @swaldhoff @mwisepnnl @cahartin See above, and please add your ORCID IDs if you want (you can also just email/post them here and I'll add).

**Comment by bpbond** [comment]
FYI - Barbara Wentzel, a research librarian at PNNL, said feel free to get in touch via email, phone, or Skype if you have questions about the value/utility of ORCID IDs.

**Pull request merged**
