### PR TITLE
Compress files

### PR DESCRIPTION
**Pull request by bpbond**
Shrinks `inst/` from 129 MB to 78 MB.

### CODE REVIEW

**Comment by rplzzz** [comment]
@bpbond , are you able to read these compressed files?  When I try I get an error:
```
> l100area <- read.csv('L100.Land_type_area_ha.csv.zip')
Error in read.table(file = file, header = header, sep = sep, quote = quote,  : 
  duplicate 'row.names' are not allowed
In addition: Warning messages:
1: In read.table(file = file, header = header, sep = sep, quote = quote,  :
  line 1 appears to contain embedded nulls
2: In read.table(file = file, header = header, sep = sep, quote = quote,  :
  line 3 appears to contain embedded nulls
3: In read.table(file = file, header = header, sep = sep, quote = quote,  :
  line 4 appears to contain embedded nulls
4: In scan(file = file, what = what, sep = sep, quote = quote, dec = dec,  :
  embedded nul(s) found in input
```
Reading the uncompressed csv file works as expected, so I'm wondering if something got messed up in the compression process.  Also, there appears to be some Mac junk folded in with the data, which may or may not be related:
```
% unzip L100.Land_type_area_ha.csv.zip 
Archive:  L100.Land_type_area_ha.csv.zip
  inflating: L100.Land_type_area_ha.csv  
   creating: __MACOSX/
  inflating: __MACOSX/._L100.Land_type_area_ha.csv  
```

Finally, R supports xz compression, which looks like it creates smaller files than zip, which is kind of an archaic algorithm:
```
% du -h L100*
 18M	L100.Land_type_area_ha.csv
3.9M	L100.Land_type_area_ha.csv.zip
2.4M	L100.whatever.csv.xz
```

**Comment by bpbond** [comment]
Interesting. For me, `readr::read_csv` reads that file fine, but `read.csv` does not.

I agree about using zip--I've been doing just because it seems to be what everyone, especially on the Windows side, has access to and is expecting. xz or gz would be great to shift to though.

**Comment by rplzzz** [comment]
The point is that the user doesn't ever have to uncompress the files.  R has the ability to read from compressed connections transparently.

`read_csv` worked for me once I remembered that you had to specify the comment character.

**Comment by bpbond** [comment]
I agree, but people regularly want/need to go _look_ at those files, e.g. to check formats/headers etc., and I was concerned that seeing `.(g|x)z$` would be confusing.

**Comment by bpbond** [comment]
As you mentioned in #39 we're going to want to do some V1.1 cleanup on all files, I suspect. I'll add a note to that issue re potentially changing compression algorithm.

**Pull request merged**
