### PR TITLE
Added source to metadata

### PR DESCRIPTION
**Pull request by swd-turner**
see issue #165

### CODE REVIEW

**Comment by bpbond** [comment]
Sean, should this just be pushed into #236, or did you make it stand-alone for a reason? Not a big deal either way.

**Comment by swd-turner** [comment]
Ok... didn't do it this way for any particular reason. Shall I go ahead and push to #236 or will I leave it as is now the pull request as already been opened?

**Comment by bpbond** [comment]
Sure, leave it now. Just wondering. Thanks.

**Comment by swd-turner** [comment]
My thinking was that I should do the pull request because the issue was raised initially when I was working on another chunk (#196), which has already been merged to master.

**Pull request merged**
