### PR TITLE
Silence "no visible binding" notes on package check.

### PR DESCRIPTION
**Pull request by rplzzz**
These are caused by the nonstandard evaluation in dplyr functions.
They are harmless, but the deluge of notes can obscure more serious
messages.  We can silence them by creating dummy bindings for any
symbols used only in NSE expressions.

This change set fixes the notes in all currently merged modules.  After this it will be up to each author to ensure that the modules they are committing don't produce these notes.

### CODE REVIEW

**Comment by bpbond** [comment]
I was wondering if you were working on this...thanks.

```R
[1] "module_aglu_LA107.an_IMAGE_R_C_Sys_Fd_Y"
 Show Traceback
 
 Rerun with Debug
 Error: invalid subscript type 'NULL' 
```

**Comment by rplzzz** [comment]
Error appears to be on this line (LA107.an_IMAGE_R_C_Sys_Fd_Y.R)
```
mutate(GCAM_region_ID =  left_join_error_no_match(., iso_GCAM_regID, by = c("iso"))$GCAM_region_ID)
```
Why did we even allow this?  Having a join _inside_ a mutate is very weird.  Apparently it interacts in some way I haven't quite figured out yet with the assignments at the top of the file.

**Comment by bpbond** [comment]
Ugh, ugh, ugh. Slipped through.

I've definitely been trying to crack down (e.g. #404 ) more consistently on funky/bizarre stuff like that.

**Comment by bpbond** [comment]
...anyway one of us can fix or happy to tag original author and ask them to do it.

**Comment by rplzzz** [comment]
I'm just going to change the `$` operator and move on.  Your call whether you want to fix the other stuff.

**Comment by bpbond** [comment]
@aarony2j let me draw your attention to this - as you seem to be the primary offender :)  - please don't use `$`inside dplyr functions! It tends to cause problems.

**Comment by aarony2j** [comment]
@bpbond Okay, now I know.

**Pull request merged**
