### PR TITLE
Aglu traceback

### PR DESCRIPTION
**Pull request by bpbond**
@kvcalvin Remove `temp-data-inject` files from `aglu`
#729

### CODE REVIEW

**Comment by bpbond** [comment]
Note - looks like "veg.carbon.density" field of `L2252.LN5_MgdCarbon_bio` doesn't match.

**Comment by kvcalvin** [comment]
@bpbond: this is the note I had on that error from before: "still fails the oldnew test on one table for a small number of rows. I think this has to do with bioenergy yield differentiation between hi/lo input, but I couldn't get my fix to work"

Essentially, there is a bug in the data used for DSR where bioenergy yields differ between hi & lo technologies, but veg.carbon.density doesn't. This has been fixed in the integration branch, but not here. I was trying to reverse engineer the issue here but couldn't get it right.

**Comment by kvcalvin** [comment]
@bpbond: If I had to guess, this PR may pass tests as soon as Pralit's GCAM5 changes are merged onto master.

**Comment by bpbond** [comment]
Oooh that'd be exciting. Thanks @kvcalvin 🤞

**Comment by kvcalvin** [comment]
@bpbond I'm still having rounding issues. Not sure what to do now.

**Comment by kvcalvin** [comment]
@bpbond: I have added `FLAG_NO_TEST` to `L2252.LN5_MgdCarbon_bio`. I think the test is failing due to inconsistent rounding between the old and new data systems. I'm going to post figures comparing old and new...for mature age and soil carbon, things match exactly. For vegetation carbon, there are a few region/tech combinations where one rounds up and one rounds down resulting in small inconsistencies.

**Comment by kvcalvin** [comment]
soilcarbon

**Comment by kvcalvin** [comment]
matureage

**Comment by kvcalvin** [comment]
vegcarbon

**Comment by kvcalvin** [comment]
For all three, old is on the x axis and new is on the y

**Comment by bpbond** [comment]
Hi @kvcalvin - this is really up to you--are these levels of "errors" acceptable? Presumably, by adding `FLAG_NO_TEST`, you think yes. In that case it works for me.

**Comment by bpbond** [comment]
>Inputs aglu/A_LandLeaf3, L181.YieldMult_R_bio_GLU_irr don't appear as precursors for any outputs - chunk module_aglu_L2252.land_input_5_irr_mgmt

@kvcalvin can you fix this please?

**Comment by bpbond** [comment]
Not sure what's going on here:

```
[1] "- make 1.08"
[1] "module_energy_L222.en_transformation"
[1] "- make 0.84"
[1] "module_energy_L223.electricity"
 Error: Column `capacity.factor` not found 
```

**Comment by kvcalvin** [comment]
Closing this one since there is something broken.

**Pull request closed without merging**
