### PR TITLE
Change to usethis::use_data because devtools version deprecated

### LINKED ISSUE #1075: Shift away from devtools::use_data
`devtools` v. 2.0.1.:
```
11: 'devtools::use_data' is deprecated.
Use 'usethis::use_data()' instead.
See help("Deprecated") and help("devtools-deprecated").
```

This applies to both gcamdata and gcamdata.compdata.

### PR DESCRIPTION
**Pull request by bpbond**
Closes #1075

### CODE REVIEW

**Comment by bpbond** [comment]
@pralitp Bah this is repeatedly timing out (because of tests) again.

**Comment by pralitp** [comment]
Bah, indeed.  Was there some change in particular that pushed us over the edge?

On a kind of related note.  What do you think about adding `PKGTYPE binary` to the appveyor config to fix it failing due to trying to compile `dplyr` from source?

**Comment by rplzzz** [comment]
> 
> On a kind of related note. What do you think about adding `PKGTYPE binary` to the appveyor config to fix it failing due to trying to compile `dplyr` from source?

I've been doing this on all of my repositories.  You can do it in the `appveyor.yml` file, but I've found it more convenient to do it from the settings page on appveyor.

**Comment by bpbond** [comment]
Some particular change–not that I know of.

`PKGTYPE binary`–sounds great. Tired of watching it fail to compile dplyr. Poking around the AppVeyor settings...hmm, how do I do this?

**Comment by rplzzz** [comment]
> `PKGTYPE binary`–sounds great. Tired of watching it fail to compile dplyr. Poking around the AppVeyor settings...hmm, how do I do this?

Here's a screenshot of the relevant settings page for one of my other projects.  I set the type to `win.binary` because that's what was suggested in the discussion on some issue or another, and it appears to work.
image

**Comment by pralitp** [comment]
Interesting, I don't think I have messed with those settings.  I was going to try:
https://github.com/krlmlr/r-appveyor#environment-variables

**Comment by bpbond** [comment]
Thanks @rplzzz @pralitp . Restarting the AppVeyor builds...

**Comment by pralitp** [comment]
I can't figure out how to get the AppVeyor tests to restart.  Maybe I never set up my account properly?

**Comment by bpbond** [comment]
@pralitp Not sure; for me it's right at top right:
Screen Shot 2019-07-05 at 5 28 15 PM

**Pull request merged**
