### PR TITLE
Prune unneeded data as driver runs

### PR DESCRIPTION
**Pull request by bpbond**
This addresses the issues raised #522, in particular memory usage of the driver. It involves significant changes to the driver's behavior: now no data are returned by default, but the user can request (via a variety of parameters) that certain data be returned.

~I can't figure out why the timeshift test is currently dying. Will come back and fix this, but thought it would be useful for now to open a PR for review and testing.~

### CODE REVIEW

**Comment by bpbond** [comment]
It would be good to have a bunch of people test this, since it's a big change. I've tagged you @abigailsnyder @pralitp but if busy or you'd prefer not to, no worries, just reassign to someone else. Thanks.

**Comment by pralitp** [comment]
Hey @bpbond, I just checked out the branch and gave it a go and got:

[1] "module_data_Maddison_population"
[1] "- make 0.04"
 Hide Traceback
 
 Rerun with Debug
 Error: data_list is not a character vector 
4.
stop(assertError(attr(res, "msg"))) 
3.
assert_that(is.character(data_list)) at utils-data.R#259
2.
remove_data(names(which_zero), all_data) at driver.R#220
1.
driver()

**Comment by pralitp** [comment]
Note, changing the assert to allow `is.character(data_list) || is.null(data_list)` is sufficient to solve this for me.

**Comment by bpbond** [comment]
Thanks Pralit! :doh:

**Comment by bpbond** [comment]
Though it didn't fail on Travis. Huh. Anyway, tweaked that assertion.

**Comment by bpbond** [comment]
Adding Corinne as a reviewer - please test if you have time.

**Comment by bpbond** [comment]
@pralitp re your question in #522 , I see one "Skipping XML conversion as global option gcamdata.use_java is not TRUE" message but would have expected many? Anyway please check on your system.

**Comment by pralitp** [comment]
Yup, I verified they get generated correctly.  The message only gets printed once per your recommendation so it doesn't spew hundreds of warning messages (was especially an issue when the XML files were all written at the end).

**Comment by pralitp** [comment]
@bpbond, what is the correct name to use for the parameter `return_inputs_of` or `return_outputs_of`?  I tried something like the following but doesn't seem to work.  Using `return_data_names` seems to work as expected.
```R
x <- driver(return_inputs_of = c("module_aglu_batch_demand_input_xml"))
x
$<NA>
NULL
```

**Comment by bpbond** [comment]
@pralitp Um...I would expect that to work. 🐛

**Comment by bpbond** [comment]
As a workaround until I investigate (soon), what about 

```R
x <- driver(stop_before = "module_aglu_batch_demand_input_xml")
```
?

**Comment by pralitp** [comment]
Huh, that works.  Also note to self pick a chunk that gets run earlier in the system for testing.

**Comment by bpbond** [comment]
Thanks @pralitp . Sorry about that. It's tricky to write tests for the driver, because it interacts with so many parts of the data system...but I should have caught that.

**Comment by pralitp** [comment]
No worries at all.  I figured you were asking us to take it for a test spin to iron out these kinks sooner rather than later anyway.

**Comment by bpbond** [comment]
@abigailsnyder @pralitp @cahartin If possible it would be great to get this merged in next 48 hours, so if you have feedback or find bugs, please let me know by end of tomorrow if possible. Thanks.

**Comment by abigailsnyder** [comment]
@bpbond I _should_ have time to look at it after about 12pm tomorrow. So I'll be sure to prioritize this at that point

**Comment by cahartin** [comment]
@bpbond on it after my 2pm call!

**Comment by cahartin** [comment]
@bpbond
It looks like you and Pralit addressed this earlier...?  

 `1] "module_modeltime_batch_modeltime_xml"
[1] "- make 0.00"
Skipping XML conversion as global option gcamdata.use_java is not TRUE`

**Comment by bpbond** [comment]
@cahartin yup thanks. He confirmed that behavior is good.

**Comment by pralitp** [comment]
@cahartin, sort of. That is not affected by this PR.

By default the options `options("gcamdata.use_java")` is `FALSE` so as to assume people don't have Java installed and therefore don't attempt to run the XML conversion.  If you do want the XML files and do have Java installed you can simply run options("gcamdata.use_java" = TRUE)` and you will no longer get that warning.

**Comment by cahartin** [comment]
Is the only option in `all_data`, to return an empty tibble?

Other than that, i went through and ran all of the other options and everything seems to be working.  However, I went to try and do the `debug(module.....)` step and I can't get that working when I stop at particular chunk. This has probably changed since this driver update...?

**Comment by bpbond** [comment]
@cahartin That should be the same as before:
```R
driver(stop_before = "module_aglu_LA100.FAO_downscale_ctry") -> x
debug(gcamdata:::module_aglu_LA100.FAO_downscale_ctry)
gcamdata:::module_aglu_LA100.FAO_downscale_ctry("MAKE", x)
```

**Comment by cahartin** [comment]
@bpbond ah, gotcha, that works on my end.  I can't find any issues with this branch.

**Comment by abigailsnyder** [comment]
I just checked out and ran the driver as-is on my machine. 
It looks like all the outputs were written correctly, based on timestamps in the output folders. 
But I find the "returning 0 tibbles." bit weird in the following:
```
[1] "module_aglu_batch_demand_input_xml"
[1] "- make 0.05"
Writing chunk data...
Returning 0 tibbles.
All done.
```

I would expect plenty of people to assume that's an error?

**Comment by bpbond** [comment]
Good suggestion @abigailsnyder - thanks!

**Pull request merged**
