### PR TITLE
missing_data function

### PR DESCRIPTION
**Pull request by bpbond**
Add a `missing_data` function that returns a tibble with appropriate structure and attributes. This eliminates a lot of repetition throughout the code, and centralizes the handling of this.

Addresses #801 .

### CODE REVIEW

**Comment by bpbond** [comment]
@rplzzz @pralitp Can one of you, at your convenience, check out, build, and test this PR? Tests are failing on Travis but I can't see any problem on my machine. Not sure what's going on. Thanks.

**Comment by rplzzz** [comment]
I'll take a look at it.  It will probably be tomorrow before I get to it though.

**Comment by pralitp** [comment]
When I try to run this branch I get:
```
[1] "module_energy_LA100.IEA_downscale_ctry"
Error in add_title(., "IEA energy balances downscaled to 201 countries by iso code, FLOW, PRODUCT, and historical year") : 
  Not allowed to overwrite current title 'Data not created'
13.
stop("Not allowed to overwrite current title '", attr(x, ATTR_TITLE), 
    "'") at utils-data.R#28
12.
add_title(., "IEA energy balances downscaled to 201 countries by iso code, FLOW, PRODUCT, and historical year") 
11.
function_list[[i]](value) 
10.
freduce(value, `_function_list`) 
9.
`_fseq`(`_lhs`) 
8.
eval(quote(`_fseq`(`_lhs`)), env, env) 
7.
eval(quote(`_fseq`(`_lhs`)), env, env) 
6.
withVisible(eval(quote(`_fseq`(`_lhs`)), env, env)) 
5.
L100.IEA_en_bal_ctry_hist %>% add_title("IEA energy balances downscaled to 201 countries by iso code, FLOW, PRODUCT, and historical year") %>% 
    add_units("ktoe and GWh") %>% add_legacy_name("L100.IEA_en_bal_ctry_hist") %>% 
    add_precursors("L100.Pop_thous_ctry_Yh", "energy/en_OECD", 
        "energy/en_nonOECD", "energy/mappings/IEA_product_downscaling",  ... at zchunk_LA100.IEA_downscale_ctry.R#313
4.
module_energy_LA100.IEA_downscale_ctry("MAKE", structure(list(
    L100.Pop_thous_ctry_Yh = structure(list(iso = c("afg", "afg", 
    "afg", "afg", "afg", "afg", "afg", "afg", "afg", "afg", "afg", 
    "afg", "afg", "afg", "afg", "afg", "afg", "afg", "afg", "afg",  ... 
3.
do.call(chunk, list(driver.MAKE, all_data)) at driver.R#14
2.
run_chunk(chunk, all_data[input_names]) at driver.R#252
1.
driver() 
```

**Comment by pralitp** [comment]
@bpbond, progress?  Travis still fails but Appveryor now passes.

**Comment by bpbond** [comment]
Taking a look...

**Comment by bpbond** [comment]
This continues to pass all test on my machine.

**Comment by pralitp** [comment]
Well, looking at the log it is failing it the tests that are marked travis only so that mystery is solved I guess.  It has something to do with:
```
expect_identical(dim(gcamdata:::GCAM_DATA_MAP), dim(gcam_data_map), info =
                       "GCAM_DATA_MAP size doesn't match.  Rerun generate_package_data to update.")
    expect_identical(gcamdata:::GCAM_DATA_MAP$name, gcam_data_map$name, info =
                       "GCAM_DATA_MAP name doesn't match.  Rerun generate_package_data to update.")
    expect_identical(gcamdata:::GCAM_DATA_MAP$output, gcam_data_map$output,
                     info = "GCAM_DATA_MAP output doesn't match")
    expect_identical(gcamdata:::GCAM_DATA_MAP$precursors,
                     gcam_data_map$precursors, info =
                       "GCAM_DATA_MAP precursors doesn't match.  Rerun generate_package_data to update.")
``

So I'm currently educating myself about what is supposed to be going on here.

**Comment by bpbond** [comment]
Ping me if useful (as I wrote that code, and came up with the whole GCAM_DATA_MAP thing). Otherwise, I should have time to return to this next week. Thanks.

**Comment by bpbond** [comment]
No idea why this was failing before...but it's not now. 🎉   Waiting on your review @rplzzz or @pralitp

**Pull request merged**
