### PR TITLE
Modeltime_xml_check

### PR DESCRIPTION
**Pull request by kdorheim**
This change will allow the model time xmls to pass the xml tests.
```
 run-xml-tests.py ../old-xml/modeltime-xml ../new-xml/modeltime
3 files tested.
0 missing output files.
0 file discrepancies.
```
 See #619 for more details. 

gcamdata will still pass package checks but `L200.hector.csv` will *fail* the old new test.

### CODE REVIEW

**Comment by bpbond** [comment]
We should change the comparison file too, right?

**Comment by kdorheim** [comment]
Make the corresponding change in the old data system replace the csv in `gcamdata\tests\testthat\comparison_data`?

**Comment by bpbond** [comment]
I think so. We want tests to pass before merging. This can be considered part of the GCAM5 changes that @pralitp I doing I think.

**Comment by kdorheim** [comment]
This change is actually part of another PR.

**Pull request closed without merging**
