### PR TITLE
Add missing XML file chunks

### PR DESCRIPTION
**Pull request by bpbond**
As part of #619 I added these missing XML-generating chunks, but it’s throwing an error.

```
[1] "module_climate_xml_batch_magicc.xml"
 Show Traceback
 
 Rerun with Debug
 Error: Unknown columns 'default.emiss.file' 
```

@pralitp could use help

### CODE REVIEW

**Comment by pralitp** [comment]
@bpbond it looks like somehow we missed a change (maybe when we switched from core data system to integration/water-ssp data system since `module_modeltime_L200.modeltime` was amongst the first to get translated?

Anyways, I recreated it however I'm worried old/new will fail now.  Where is the old data stored that is checked against and if it does indeed fail I could just update the old CSV files right?

**Comment by bpbond** [comment]
Thank you! Looks good and is passing tests.

**Comment by bpbond** [comment]
P.S. the data it's compared against is stored in `tests/testthat/comparison-data`

**Comment by pralitp** [comment]
Thanks, yea I poked around and updated it.

**Pull request merged**
